# Describes the format for available binary_sensor services

ffmpeg_start:
  description: Send a start command to a ffmpeg based sensor.

  fields:
    entity_id:
      description: Name(s) of entites that will start. Platform dependent.
      example: 'binary_sensor.ffmpeg_noise'

ffmpeg_stop:
  description: Send a stop command to a ffmpeg based sensor.

  fields:
    entity_id:
      description: Name(s) of entites that will stop. Platform dependent.
      example: 'binary_sensor.ffmpeg_noise'

ffmpeg_restart:
  description: Send a restart command to a ffmpeg based sensor.

  fields:
    entity_id:
      description: Name(s) of entites that will restart. Platform dependent.
      example: 'binary_sensor.ffmpeg_noise'
