# Describes the format for available camera services

enable_motion_detection:
  description: Enable the motion detection in a camera

  fields:
    entity_id:
      description: Name(s) of entities to enable motion detection
      example: 'camera.living_room_camera'

disable_motion_detection:
  description: Disable the motion detection in a camera
  
  fields:
    entity_id:
      description: Name(s) of entities to disable motion detection
      example: 'camera.living_room_camera'
